# Generated by Django 5.2.4 on 2025-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0002_borrowrecord_due_date_alter_borrowrecord_borrow_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowrecord",
            old_name="borrow_date",
            new_name="borrowed_at",
        ),
        migrations.RenameField(
            model_name="borrowrecord",
            old_name="return_date",
            new_name="returned_at",
        ),
        migrations.RemoveField(
            model_name="borrowrecord",
            name="due_date",
        ),
    ]
